---
- hosts: all
  tasks:
    - name: Update Windows
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        log_path: C:\ansible_wu.txt
