---
- name: This sets up an apache2 webserver
  hosts: all
  tasks:
  - name: Install apache2 packages
    apt:
      name: apache2
      state: present
  - name: ensure apache2 is running
    service:
      name: apache2
      state: started
