---
- name: This sets up snmp on server
  hosts: all
  tasks:
  - name: Install snmp packages
    apt:
      name: net-snmp
      state: latest
  - name: Enable snmp service
    service:
     name: snmpd
     enabled: yes
  - name: Insert New line
    blockinfile:
     path: /etc/snmp/snmpd.conf
     insertafter: "rocommunity"
     content: |
      rocommunity public 192.168.100.100
  - name: Restart SNMP Service
    service:
     name: snmpd
     state: restarted
